version: '3.8'
services:
  dotnet_postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: "mysecretdb"
      POSTGRES_USER: "mysecretuser"
      POSTGRES_PASSWORD: "mysecretpassword"
    ports:
      - "5432:5432" 
    
  dotnet_main:
    image: dotnet-web
    environment:
      ConnectionStrings__Default: Server=dotnet_postgres;Port=5432;Database=mysecretdb;User Id=mysecretuser;Password=mysecretpassword
    build:
      context: .
      dockerfile: Dotnet.Homeworks.MainProject/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - dotnet_postgres   
  
#  dotnet_rabbitmq:
#    image: rabbitmq:3-alpine
#    
#  dotnet_minio:
#    image: minio/minio:latest
#    
#  dotnet_mongodb:
#    image: mongo:latest
#    
#  dotnet_jaeger:
#    image: jaegertracing/all-in-one:latest
#
#  dotnet_mailing:
#    image: dotnet-web
#    
#  dotnet_storage:
#    image: dotnet-web