version: '3.8'
services:
  dotnet_postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: "mysecretdb"
      POSTGRES_USER: "mysecretuser"
      POSTGRES_PASSWORD: "mysecretpassword"
    ports:
      - "5432:5432"
  
  dotnet_main:
    image: dotnet-web
    environment:
      ConnectionStrings__Default: Server=dotnet_postgres;Port=5432;Database=mysecretdb;User Id=mysecretuser;Password=mysecretpassword
      RabbitMqConfig__Hostname: mysecrethostname
      RabbitMqConfig__Username: mysecretusername
      RabbitMqConfig__Password: mysecretpassword1!
    build:
      context: .
      dockerfile: Dotnet.Homeworks.MainProject/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - dotnet_postgres
      - dotnet_rabbitmq

  dotnet_rabbitmq:
    image: rabbitmq:3-alpine
    hostname: mysecrethostname
    environment:
      RABBITMQ_DEFAULT_USER: mysecretusername
      RABBITMQ_DEFAULT_PASS: mysecretpassword1!
    ports:
      - "5672:5672" 

  dotnet_mailing:
    image: dotnet-web
    build:
      context: .
      dockerfile: Dotnet.Homeworks.Mailing.API/Dockerfile
    ports:
      - "5001:80"
    environment:
      EmailConfig__Email: mysecretemail@gmail.com
      EmailConfig__Host: mysecrethost.gmail.com
      EmailConfig__Port: 000
      EmailConfig__Password: mysecretemailpassword1!
      RabbitMqConfig__Password: mysecretpassword1!
      RabbitMqConfig__Username: mysecretusername
      RabbitMqConfig__Hostname: mysecrethostname
    depends_on:
      - dotnet_rabbitmq
#  dotnet_minio:
#    image: minio/minio:latest
#    
#  dotnet_mongodb:
#    image: mongo:latest
#    
#  dotnet_jaeger:
#    image: jaegertracing/all-in-one:latest
#
#    
#  dotnet_storage:
#    image: dotnet-web